# Generated by Django 3.0.1 on 2020-03-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(max_length=50, verbose_name='Name of pay per view')),
                ('image', models.TextField(verbose_name='Image of pay per view')),
                ('date', models.DateField(blank=True, verbose_name='Date of pay per view')),
            ],
        ),
    ]
