# Generated by Django 3.0.1 on 2020-03-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppv',
            name='date',
        ),
    ]
