# Generated by Django 3.0.1 on 2020-03-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0002_remove_ppv_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppv',
            name='ic_title_changes',
            field=models.IntegerField(default=0, verbose_name='Number of intercontinental championship changes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppv',
            name='ic_title_matches',
            field=models.IntegerField(default=0, verbose_name='Number of intercontinental championship matches'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppv',
            name='tag_title_changes',
            field=models.IntegerField(default=0, verbose_name='Number of tag team championship changes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppv',
            name='tag_title_matches',
            field=models.IntegerField(default=0, verbose_name='Number of tag team championship matches'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppv',
            name='us_title_changes',
            field=models.IntegerField(default=0, verbose_name='Number of united states championship changes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppv',
            name='us_title_matches',
            field=models.IntegerField(default=0, verbose_name='Number of united states championship matches'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppv',
            name='wh_title_changes',
            field=models.IntegerField(default=0, verbose_name='Number of world heavyweight changes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppv',
            name='wh_title_matches',
            field=models.IntegerField(default=0, verbose_name='Number of world heavyweight championship matches'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppv',
            name='wwe_title_changes',
            field=models.IntegerField(default=0, verbose_name='Number of wwe championship changes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppv',
            name='wwe_title_matches',
            field=models.IntegerField(default=0, verbose_name='Number of wwe championship matches'),
            preserve_default=False,
        ),
    ]
