# Generated by Django 3.0.1 on 2020-03-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0005_auto_20200327_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matches',
            new_name='Matche',
        ),
    ]
