# Generated by Django 3.0.1 on 2020-03-27 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0006_auto_20200327_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of pay per view')),
                ('result', models.CharField(max_length=150, verbose_name='Result of match')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title that was defended')),
            ],
        ),
        migrations.DeleteModel(
            name='Matche',
        ),
        migrations.AddField(
            model_name='match',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppvs.Title'),
        ),
    ]
