# Generated by Django 3.0.1 on 2020-03-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0007_auto_20200327_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='image',
            field=models.TextField(default='', verbose_name='Image of the title that was defended'),
            preserve_default=False,
        ),
    ]
