# Generated by Django 3.0.1 on 2020-03-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0009_title_ppv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='ppv',
        ),
    ]
