# Generated by Django 3.0.1 on 2020-03-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0011_title_ppv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='ppv',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ppvs.PPV'),
        ),
    ]
