# Generated by Django 3.0.1 on 2020-03-27 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0012_auto_20200327_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='ppv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppvs.PPV'),
        ),
    ]
