# Generated by Django 3.0.1 on 2020-03-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0013_auto_20200327_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='ppv',
            new_name='special_ppv',
        ),
    ]
