# Generated by Django 3.0.1 on 2020-03-27 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0014_auto_20200327_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='special_ppv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ppvs.PPV'),
            preserve_default=False,
        ),
    ]
