# Generated by Django 3.0.1 on 2020-03-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0015_auto_20200327_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='special_ppv',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
