# Generated by Django 3.0.1 on 2020-03-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0016_auto_20200327_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title that was defended')),
                ('image', models.TextField(verbose_name='Image')),
                ('ppv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppvs.PPV')),
            ],
        ),
    ]
