# Generated by Django 3.0.1 on 2020-03-27 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0017_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=150, verbose_name='Result of the match')),
                ('date', models.DateField(verbose_name='Date of the match')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppvs.Title')),
            ],
        ),
    ]
