# Generated by Django 3.0.1 on 2020-03-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0018_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='ppv',
        ),
        migrations.AddField(
            model_name='match',
            name='ppv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ppvs.PPV'),
            preserve_default=False,
        ),
    ]
