# Generated by Django 3.0.1 on 2020-03-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0019_auto_20200327_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(max_length=500, verbose_name='Result of the match'),
        ),
    ]
