# Generated by Django 3.0.1 on 2020-03-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0020_auto_20200327_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.TextField(verbose_name='Result of the match'),
        ),
    ]
