# Generated by Django 3.0.1 on 2020-04-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0021_auto_20200327_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(max_length=300, verbose_name='Result of the match'),
        ),
    ]
