# Generated by Django 3.0.1 on 2020-04-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0022_auto_20200424_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='title_change',
            field=models.BooleanField(default=False, verbose_name='Title change?'),
            preserve_default=False,
        ),
    ]
