# Generated by Django 3.0.1 on 2020-04-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0023_match_title_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.TextField(verbose_name='Result of the match'),
        ),
    ]
