# Generated by Django 3.0.1 on 2020-05-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0024_auto_20200424_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Titles',
        ),
    ]
