# Generated by Django 3.0.1 on 2020-06-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppvs', '0025_auto_20200514_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppv',
            name='gif',
            field=models.TextField(blank=True, verbose_name='GIFof pay per view'),
        ),
    ]
