# Generated by Django 3.0.1 on 2020-03-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='ic_title_wins',
            field=models.IntegerField(default=0, verbose_name='Number of intercontinental championship wins'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrestler',
            name='tag_title_wins',
            field=models.IntegerField(default=0, verbose_name='Number of tag team championship wins'),
            preserve_default=False,
        ),
    ]
