# Generated by Django 3.0.1 on 2020-03-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0002_auto_20200316_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='us_title_wins',
            field=models.IntegerField(default=0, verbose_name='Number of United States championship wins'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrestler',
            name='wh_title_wins',
            field=models.IntegerField(default=0, verbose_name='Number of World championship wins'),
            preserve_default=False,
        ),
    ]
