# Generated by Django 3.0.1 on 2020-03-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0003_auto_20200316_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='ic_title_days',
            field=models.IntegerField(default=0, verbose_name='Days intercontinental championship was held'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrestler',
            name='tag_title_days',
            field=models.IntegerField(default=0, verbose_name='Days tag team championship was held'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrestler',
            name='us_title_days',
            field=models.IntegerField(default=0, verbose_name='Days United States championship was held'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrestler',
            name='wh_title_days',
            field=models.IntegerField(default=0, verbose_name='Days world championship was held'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrestler',
            name='wwe_title_days',
            field=models.IntegerField(default=0, verbose_name='Days WWE championship was held'),
            preserve_default=False,
        ),
    ]
