# Generated by Django 3.0.1 on 2020-03-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0004_auto_20200319_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='info',
            field=models.TextField(default=0, verbose_name='Brief info about wrestler'),
            preserve_default=False,
        ),
    ]
