# Generated by Django 3.0.1 on 2020-03-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0005_wrestler_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrestler',
            name='info',
        ),
    ]
