# Generated by Django 3.0.1 on 2020-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0006_remove_wrestler_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='info',
            field=models.TextField(default='No info', verbose_name='Brief info about wrestler'),
            preserve_default=False,
        ),
    ]
