# Generated by Django 3.0.1 on 2020-03-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0007_wrestler_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='kotr',
            field=models.TextField(default='', verbose_name='King of the ring tournament wins'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrestler',
            name='mitb',
            field=models.TextField(default='', verbose_name='Money in the bank contract wins'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrestler',
            name='rr',
            field=models.TextField(default='', verbose_name='Royal Rumble Wins'),
            preserve_default=False,
        ),
    ]
