# Generated by Django 3.0.1 on 2020-03-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0008_auto_20200323_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='kotr',
            field=models.TextField(blank=True, verbose_name='King of the ring tournament wins'),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='mitb',
            field=models.TextField(blank=True, verbose_name='Money in the bank contract wins'),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='rr',
            field=models.TextField(blank=True, verbose_name='Royal Rumble Wins'),
        ),
    ]
