# Generated by Django 3.0.1 on 2020-03-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0009_auto_20200323_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='photo',
            field=models.TextField(default='', verbose_name='Photo of wrestler'),
            preserve_default=False,
        ),
    ]
