# Generated by Django 3.0.1 on 2020-03-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0010_wrestler_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='main_page',
            field=models.TextField(default='', verbose_name='Photo of wrestler for main page'),
            preserve_default=False,
        ),
    ]
