# Generated by Django 3.0.1 on 2020-03-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0011_wrestler_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='title_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
