# Generated by Django 3.0.1 on 2020-03-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0012_wrestler_title_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrestler',
            name='title_id',
        ),
    ]
