# Generated by Django 3.0.1 on 2020-05-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0013_remove_wrestler_title_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='finisher',
            field=models.TextField(blank=True, verbose_name='Finisher of wrestler'),
        ),
    ]
