# Generated by Django 3.0.1 on 2020-05-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0015_auto_20200517_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='finisher2',
            field=models.TextField(blank=True, verbose_name='Finisher of wrestler'),
        ),
    ]
