# Generated by Django 3.0.1 on 2020-05-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0016_wrestler_finisher2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='finisher2',
            field=models.TextField(blank=True, verbose_name='Finisher of wrestler 3'),
        ),
    ]
