# Generated by Django 3.0.1 on 2020-05-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0018_auto_20200517_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jerry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.TextField(verbose_name='aazaz')),
            ],
        ),
    ]
