# Generated by Django 3.0.1 on 2020-05-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0019_jerry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jerry',
        ),
    ]
