# Generated by Django 3.0.1 on 2020-05-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0020_delete_jerry'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='eu_title_days',
            field=models.IntegerField(default=0, verbose_name='Days European championship was held'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrestler',
            name='eu_title_wins',
            field=models.IntegerField(default=0, verbose_name='Number og European Championship wins'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrestler',
            name='hc_title_days',
            field=models.IntegerField(default=0, verbose_name='Days Hardcore championship was held'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrestler',
            name='hc_title_wins',
            field=models.IntegerField(default=0, verbose_name='Number of Hardcore Championship wins'),
            preserve_default=False,
        ),
    ]
