# Generated by Django 3.0.1 on 2020-05-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0021_auto_20200521_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='tag_teams',
            field=models.TextField(default=0, verbose_name='Tag teams or stable wrestler was a part of'),
            preserve_default=False,
        ),
    ]
