# Generated by Django 3.0.1 on 2020-05-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0022_wrestler_tag_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='tag_teams',
            field=models.TextField(blank=True, verbose_name='Tag teams or stable wrestler was a part of'),
        ),
    ]
