# Generated by Django 3.0.1 on 2020-05-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0023_auto_20200522_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='tag_teams2',
            field=models.TextField(blank=True, verbose_name='Tag teams or stable wrestler was a part of'),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='tag_teams3',
            field=models.TextField(blank=True, verbose_name='Tag teams or stable wrestler was a part of'),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='tag_teams4',
            field=models.TextField(blank=True, verbose_name='Tag teams or stable wrestler was a part of'),
        ),
    ]
