# Generated by Django 3.0.1 on 2020-05-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0024_auto_20200522_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='tag_teams5',
            field=models.TextField(blank=True, verbose_name='Tag teams or stable wrestler was a part of'),
        ),
    ]
