# Generated by Django 3.0.1 on 2020-05-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0025_wrestler_tag_teams5'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='tag_teams6',
            field=models.TextField(blank=True, verbose_name='Tag teams or stable wrestler was a part of'),
        ),
    ]
