# Generated by Django 3.0.1 on 2020-05-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0026_wrestler_tag_teams6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='tag_teams',
            field=models.TextField(verbose_name='Tag teams or stable wrestler was a part of'),
        ),
    ]
