# Generated by Django 3.0.1 on 2020-05-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestler', '0027_auto_20200523_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='tag_teams',
            field=models.TextField(blank=True, verbose_name='Tag teams or stable wrestler was a part of'),
        ),
    ]
