# Generated by Django 3.0.1 on 2020-05-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of tag team')),
                ('photo', models.TextField(verbose_name='Photo of tag team')),
                ('main_page', models.TextField(verbose_name='Photo of tag team gor main page')),
                ('stable', models.BooleanField(verbose_name='Is Stable?')),
                ('gif1', models.TextField(verbose_name='Moment')),
                ('gif2', models.TextField(verbose_name='Moment2')),
                ('gif3', models.TextField(verbose_name='Moment3')),
                ('wwe_title_wins', models.IntegerField(verbose_name='Number of WWE championship wins')),
                ('tag_title_wins', models.IntegerField(verbose_name='Number of tag team championship wins')),
                ('ic_title_wins', models.IntegerField(verbose_name='Number of intercontinental championship wins')),
                ('wh_title_wins', models.IntegerField(verbose_name='Number of World championship wins')),
                ('us_title_wins', models.IntegerField(verbose_name='Number of United States championship wins')),
            ],
        ),
    ]
