# Generated by Django 3.0.1 on 2020-05-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagteams',
            name='info',
            field=models.TextField(default=1, verbose_name='Info about tag team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagteams',
            name='members',
            field=models.TextField(default=1, verbose_name='Members of tag team'),
            preserve_default=False,
        ),
    ]
