# Generated by Django 3.0.1 on 2020-05-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_teams', '0002_auto_20200519_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagteams',
            name='eu_title_wins',
            field=models.IntegerField(default=0, verbose_name='Number of European championship wins'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagteams',
            name='hc_title_wins',
            field=models.IntegerField(default=0, verbose_name='Number of Hardcore championship wins'),
            preserve_default=False,
        ),
    ]
