# Generated by Django 3.0.1 on 2020-03-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the championship')),
                ('wrestler', models.CharField(max_length=100, verbose_name='Name of wrestler who has held this championship')),
                ('title_reigns', models.IntegerField(verbose_name='Number of title reigns')),
                ('title_days', models.IntegerField(verbose_name='Days this title was held')),
            ],
        ),
    ]
