# Generated by Django 3.0.1 on 2020-03-16 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='title_days',
        ),
        migrations.RemoveField(
            model_name='title',
            name='title_reigns',
        ),
        migrations.RemoveField(
            model_name='title',
            name='wrestler',
        ),
        migrations.CreateModel(
            name='Title_Reigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrestler', models.CharField(max_length=100, verbose_name='Name of wrestler who has held this championship')),
                ('title_reigns', models.IntegerField(verbose_name='Number of title reigns')),
                ('title_days', models.IntegerField(verbose_name='Days this title was held')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.Title')),
            ],
        ),
    ]
