# Generated by Django 3.0.1 on 2020-03-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20200316_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title_Reigns',
            new_name='Title_Reign',
        ),
    ]
