# Generated by Django 3.0.1 on 2020-03-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20200316_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title_Reign',
        ),
    ]
