# Generated by Django 3.0.1 on 2020-03-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_delete_title_reign'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='Design of title'),
            preserve_default=False,
        ),
    ]
