# Generated by Django 3.0.1 on 2020-03-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Design of title'),
        ),
    ]
