# Generated by Django 3.0.1 on 2020-03-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_auto_20200319_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='image',
            field=models.TextField(blank=True, verbose_name='Design of title'),
        ),
    ]
