# Generated by Django 3.0.1 on 2020-03-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_auto_20200323_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='number',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
