# Generated by Django 3.0.1 on 2020-05-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0008_title_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='number',
        ),
        migrations.AddField(
            model_name='title',
            name='info',
            field=models.TextField(blank=True, verbose_name='Info about title'),
        ),
    ]
