# Generated by Django 3.0.1 on 2020-06-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0009_auto_20200526_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='gif',
            field=models.TextField(blank=True, verbose_name='Gif'),
        ),
    ]
