# Generated by Django 3.0.1 on 2020-06-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0010_title_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='info',
            field=models.TextField(verbose_name='Info about title'),
        ),
    ]
